TabletCollection/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TabletCollection.Infrastructure;

namespace TabletCollection.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            var tabletMapper = new StudentTabletMapper();


            return View(tabletMapper);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TabletCollection/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TabletCollection.DAL;
using TabletCollection.Models;
using TabletCollection.ViewModels;
using AutoMapper;

namespace TabletCollection.Controllers
{
    public class StudentsController : Controller
    {
        private TabletCollectionDBContext db = new TabletCollectionDBContext();

        // GET: Students
        public ActionResult Index(bool filter = true)
        {
            var students = from s in db.Students select s;

            if (filter)
            {
                var collectedStudentIDs = db.Collections
                    .Select(s => s.StudentID);
                students = students.Where(s => !collectedStudentIDs.Contains(s.ID));
            }
            students = students.OrderBy(s => s.FirstName).ThenBy(s => s.LastName);
            
            var studentsViewModel = Mapper.Map<List<StudentViewModel>>(students.ToList());
            return View(studentsViewModel);
        }

        [ChildActionOnly]
        public ActionResult _StudentsPartial()
        {
            var students = from s in db.Students select s;
            var collectedStudentIDs = db.Collections
                    .Select(s => s.StudentID);
            students = students
                .Where(s => !collectedStudentIDs.Contains(s.ID))
                .OrderBy(s => s.FirstName).ThenBy(s => s.LastName); ;
            var studentsViewModel = Mapper.Map<List<StudentViewModel>>(students.ToList());
            return PartialView(studentsViewModel);
        }

        // GET: Students/Details/5
        //public ActionResult Details(int? id)
        //{
        //    //not implemented dont need dont care
        //    //if (id == null)
        //    //{
        //    //    return new httpstatuscoderesult(httpstatuscode.badrequest);
        //    //}
        //    //student student = db.students.find(id);
        //    //if (student == null)
        //    //{
        //    //    return httpnotfound();
        //    //}
        //    //return view(student);
        //}

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentViewModel studentViewModel)
        {
            
            if (ModelState.IsValid)
            {
                db.Students.Add(Mapper.Map<Student>(studentViewModel));
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studentViewModel);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ImportID,FirstName,NickName,LastName,UserName,ForeignExchangeBound,ClassOf, Notes")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TabletCollection/Views/Home/About.cshtml
@model TabletCollection.Infrastructure.StudentTabletMapper
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information. This page is not doing anything.</p>

<table>
    <thead>
        <tr>
            <th>Student ID</th>
            <th>Tablet Name</th>
        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model._stutablet)
        {
            <tr>
                <td>@item.Key</td>
                <td>@item.Value</td>
            </tr>
        }


    </tbody>

</table>

TabletCollection/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="row well">
    <h2><span class="glyphicon glyphicon-bullhorn"></span>
        @ViewBag.Title.
    </h2>
    <h3>
        @ViewBag.Message
    </h3>
</div>
<address>
    1500 North Harrison Ave<br />
    Cary, NC<br />
    <abbr title="or send Dima an e-mail, and he'll respond as quick as he can">Call Kris if you have questions</abbr>
    919-228-4664
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:helpdesk@caryacademy.org">helpdesk@caryacademy.org</a><br />
</address>

TabletCollection/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1 class="text-primary">Tablet Collection</h1>
    <p class="lead">Press the button to start collecting</p>
    <span class="icon-input-btn">
        <span class="glyphicon glyphicon-briefcase"></span>
        @Html.ActionLink("Collect »", "Index", "Students", null, new { @class = "btn btn-primary btn-lg" })
    </span>
</div>

<div class="row">
    <div class="col-md-6">
        <h2 class="text-info">Quick Collect</h2>
        <p class="text-warning">Start typing in the search box</p>
        <p>
            @{Html.RenderAction(actionName: "_StudentsPartial", controllerName: "Students");}

        </p>
    </div>
    <div class="col-md-6">
        <h2 class="text-info">Recently Collected Tablets</h2>
        <p>
            @{Html.RenderAction(actionName: "_IndexPartial", controllerName: "Collections");}
        </p>
    </div>

</div>


@section scripts {
    <script>
        //Data Table in Partial view on Home page
        $(document).ready(function () {
            $("#DataTableHomePagePartial").DataTable(
                {
                    "dom": "<'col-sm-1'f>'",
                    "columnDefs": [
                        { "orderable": false, "targets": 1 }
                    ],
                }
            );
        });
    </script>
}