TabletCollection/Models/Tablet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TabletCollection.Models
{
    public class Tablet : Auditable
    {
        public int ID { get; set; }

        [Required]
        [DisplayName("Name"), MaxLength(50)]
        public string TabletName { get; set; }

        [Required]
        [Index(IsUnique = true)]
        [DisplayName("Serial#"), MaxLength(20)]
        public string SerialNo { get; set; }

        [Required]
        [DisplayName("Asset Tag"), MaxLength(20)]
        public string AssetTag { get; set; }

        [DisplayName("Fam. Purchased")]
        public bool IsPurchased { get; set; }

        [DisplayName("Addtl. Purch.")]
        public bool IsExtraPurchase { get; set; }

        [DisplayName("Purchased and PickedUp")]
        public bool IsPickedUp { get; set; }

        [DisplayName("Lenovo Buyout")]
        public bool IsVendorBuyout { get; set; }

        [MaxLength(500)]
        public string Notes { get; set; }

        public virtual ICollection<Collection> Collections { get; set; }
    }
}

TabletCollection/Controllers/CollectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TabletCollection.DAL;
using TabletCollection.Models;
using TabletCollection.ViewModels;
using AutoMapper;
using System.Data.Entity.Infrastructure;

namespace TabletCollection.Controllers
{
    public class CollectionsController : Controller
    {
        private TabletCollectionDBContext db = new TabletCollectionDBContext();

        // GET: Collections
        public ActionResult Index()
        {
            var collections = db.Collections.ToList();
            var collectionsViewModel = Mapper.Map<List<CollectionViewModel>>(collections);
            return View(collectionsViewModel);
        }

        [ChildActionOnly]
        public ActionResult _IndexPartial()
        {
            var collections = db.Collections.OrderByDescending(c => c.CreatedOn).Take(10);
           
            var collectionsViewModel = Mapper.Map<List<CollectionViewModel>>(collections.ToList());
            return PartialView(collectionsViewModel);
        }

        // GET: Collections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Collection collection = db.Collections.Find(id);
            if (collection == null)
            {
                return HttpNotFound();
            }
            var collectionViewModel = Mapper.Map<CollectionViewModel>(collection);
            return View(collectionViewModel);
        }

        // GET: Collections/Create
        public ActionResult Create(int? studentID)
        {
            if (!studentID.HasValue)
            {
                return RedirectToAction("Index", "Students", null);
            }

            var collectionViewModel = new CollectionViewModel(studentID.Value);

            var checkIfCollected = db.Collections.Where(t => t.TabletID == collectionViewModel.TabletID).FirstOrDefault();

            if (!(checkIfCollected == null))
            {
                collectionViewModel.Comments = $"Uh-Oh! Something went wrong! " +
                    $"The tablet is shown as collected. Conflicting collection ID: {checkIfCollected.Id}";
            }
            //viewbag will populate the drop down. I need "tablets" variable to limit the drop down to the tablets that weren't collected yet.
            var collectedTabletsIDs = db.Collections.Select(s => s.TabletID);
            var tablets = db.Tablets.Where(s => !collectedTabletsIDs.Contains(s.ID)).ToList();
            ViewBag.TabletID = new SelectList(tablets, "ID", "TabletName", collectionViewModel.TabletID);

            return View(collectionViewModel);
        }

        // POST: Collections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CollectionViewModel collectionViewModel)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var collection = Mapper.Map<Collection>(collectionViewModel);
                    db.Collections.Add(collection);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Students");
                    //return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
                }
            }
            catch (DataException dex)
            {
                ModelState.AddModelError(string.Empty, $"Database Error occured Copy the error message and send it to Dima</br>: {dex.Message}. / {dex.InnerException.Message} / {dex.InnerException.InnerException.Message} ");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error occured Copy the error message and send it to Dima</br>: {ex.Message}. + {ex.InnerException.Message} + {ex.InnerException.InnerException.Message}");
            }
            ViewBag.TabletID = new SelectList(db.Tablets, "ID", "TabletName", collectionViewModel.TabletID);
            return View(collectionViewModel);
        }

        // GET: Collections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Collection collection = db.Collections.Find(id);
            if (collection == null)
            {
                return HttpNotFound();
            }
            var collectionViewModel = Mapper.Map<CollectionViewModel>(collection);
            //viewbag will populate the drop down. I need "tablets" variable to limit the drop down to the tablets that weren't collected yet.
            var collectedTabletsIDs = db.Collections.Where(t=>t.TabletID != collection.TabletID).Select(s => s.TabletID);
            var tablets = db.Tablets.Where(t => !collectedTabletsIDs.Contains(t.ID)).ToList();
            ViewBag.TabletID = new SelectList(tablets, "ID", "TabletName", collectionViewModel.TabletID);
            
            return View(collectionViewModel);
        }

        // POST: Collections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CollectionViewModel collectionViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var collection = Mapper.Map<Collection>(collectionViewModel);
                    db.Entry(collection).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                //This is implemented by a virtue of having "RowVersion" field in our model and database. watch this video for details: https://youtu.be/Gi_kEbc5faQ
                ModelState.AddModelError(string.Empty, $"The record you've been trying to update was modified by another user. Please go back and try again.");
            }
            catch (DataException dex)
            {
                ModelState.AddModelError(string.Empty, $"Database Error occured Copy the error message and send it to Dima </br>: {dex.Message}. + {dex.InnerException.Message} + {dex.InnerException.InnerException.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Unexpected error occured. Copy the error message and send it to Dima {ex.Message} | {ex.InnerException.InnerException.Message}" +
                    $"{ex.InnerException.InnerException.Message}");
            }

            ViewBag.TabletID = new SelectList(db.Tablets, "ID", "TabletName", collectionViewModel.TabletID);
            return View(collectionViewModel);
        }

        // GET: Collections/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Collection collection = db.Collections.Find(id);
            if (collection == null)
            {
                return HttpNotFound();
            }
            var collectionViewModel = Mapper.Map<CollectionViewModel>(collection);
            return View(collectionViewModel);
        }

        // POST: Collections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Collection collection = db.Collections.Find(id);
            db.Collections.Remove(collection);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BFFReport()
        {
            var collections = db.Collections.Include(c=>c.Student).Include(c=>c.Tablet).OrderBy(t=>t.Tablet.TabletName);

            var _BFFViewModel = Mapper.Map<List<BFFViewModel>>(collections);
            return View("BFFReport", "~/Views/Shared/_LayoutBFF.cshtml", _BFFViewModel);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TabletCollection/Controllers/TabletsController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TabletCollection.DAL;
using TabletCollection.Models;
using TabletCollection.ViewModels;

namespace TabletCollection.Controllers
{
    public class TabletsController : Controller
    {
        private TabletCollectionDBContext db = new TabletCollectionDBContext();

        // GET: Tablets
        public ActionResult Index(bool filter = false)
        {
            var tablets = from t in db.Tablets select t;
            if (filter)
            {
                var collectedTabletsIDs = db.Collections
                    .Select(s => s.TabletID);
                tablets = tablets.Where(s => !collectedTabletsIDs.Contains(s.ID));
            }
            tablets = tablets.OrderBy(t=>t.TabletName);
            var tabletViewModels = Mapper.Map<List<TabletViewModel>>(tablets);
            //get collections IDs only when we display all tablets
            if (!filter)
            {
                tabletViewModels.ForEach(t => t.CollectionID = db.Collections.Where(c => c.TabletID == t.ID).Select(c => c.Id).FirstOrDefault());
                tabletViewModels.ForEach(t => t.IsTabletCollected = (t.CollectionID > 0) ? true : false);
            }
            //this is to show extra column in extra view for Collected tablets if all tablets are shown. Need to find a better solution perhaps.
            ViewBag.Filter = filter;
            //this line is to correctly set non-sorting column in DataTable.
            ViewBag.ExtraColumn = filter ? 7 : 8;
            return View(tabletViewModels);
        }

        // GET: Tablets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tablet tablet = db.Tablets.Find(id);
            
            if (tablet == null)
            {
                return HttpNotFound();
            }
            var tabletViewModel = Mapper.Map<Tablet>(tablet);
            return View(tabletViewModel);
        }

        // GET: Tablets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tablets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TabletViewModel tabletViewModel)
        {
            if (ModelState.IsValid)
            {
                var tablet = Mapper.Map<Tablet>(tabletViewModel);
                db.Tablets.Add(tablet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tabletViewModel);
        }

        // GET: Tablets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tablet tablet = db.Tablets.Find(id);
            if (tablet == null)
            {
                return HttpNotFound();
            }

            var tabletViewModel = Mapper.Map<TabletViewModel>(tablet);
            return View(tabletViewModel);
        }

        // POST: Tablets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TabletViewModel tabletViewModel)
        {
            if (ModelState.IsValid)
            {
                var tablet = Mapper.Map<Tablet>(tabletViewModel);

                db.Entry(tablet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tabletViewModel);
        }

        // GET: Tablets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tablet tablet = db.Tablets.Find(id);
            if (tablet == null)
            {
                return HttpNotFound();
            }
            return View(tablet);
        }

        // POST: Tablets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tablet tablet = db.Tablets.Find(id);
            db.Tablets.Remove(tablet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult BulkEdit()
        {
            var tablets = db.Tablets.OrderBy(t => t.TabletName).ToList();

            var tabletViewModels = Mapper.Map<List<TabletViewModel>>(tablets);
            return View(tabletViewModels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BulkEdit(IList<TabletViewModel> tabletsViewModel)
        {
            if (ModelState.IsValid)
            {
                var tablets = Mapper.Map<IList<Tablet>>(tabletsViewModel);

                foreach (var tablet in tablets)
                {
                    db.Entry(tablet).State = EntityState.Modified;
                   
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tabletsViewModel);
        }

        public JsonResult BulkEditJsonStream()
        {
            var tablets = db.Tablets.OrderBy(t => t.TabletName).ToList();

            var tabletViewModels = Mapper.Map<List<TabletViewModel>>(tablets);
            return Json(tabletViewModels, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BulkEditJson()
        {
            var tablets = db.Tablets.OrderBy(t => t.TabletName).ToList();

            var tabletViewModels = Mapper.Map<List<TabletViewModel>>(tablets);
            return View(tabletViewModels);
        }

        public ActionResult BulkEditPg()
        {
            var tablets = db.Tablets.OrderBy(t => t.TabletName).ToList();

            var tabletViewModels = Mapper.Map<List<TabletViewModel>>(tablets);
            return View(tabletViewModels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BulkEditPg(IList<TabletViewModel> tabletsViewModel)
        {
            if (ModelState.IsValid)
            {
                var tablets = Mapper.Map<IList<Tablet>>(tabletsViewModel);

                foreach (var tablet in tablets)
                {
                    db.Entry(tablet).State = EntityState.Modified;

                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tabletsViewModel);
        }
    }
}

TabletCollection/Views/Tablets/BulkEdit.cshtml
@model IList<TabletCollection.ViewModels.TabletViewModel>
@{
    ViewBag.Title = "Bulk Edit";
}

<div class="row well">
    <div class="offset-1 col-1">
        <h2 class="text-primary">
            <span class="glyphicon glyphicon-edit">&nbsp;</span> - Purchase Bulk Edit
        </h2>
    </div>
</div>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "batchUpdate" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <table id="indexTable" class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().TabletName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().SerialNo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().AssetTag)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().IsPurchased)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().IsPickedUp)
                    </th>*@
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(m => m[i].ID)
                            @Html.HiddenFor(m => m[i].RowVersion)
                            @Html.HiddenFor(m => m[i].CreatedBy)
                            @Html.HiddenFor(m => m[i].CreatedOn)
                            @Html.HiddenFor(m => m[i].UpdatedBy)
                            @Html.HiddenFor(m => m[i].UpdatedOn)
                            @Html.HiddenFor(m => m[i].TabletName)
                            @Html.HiddenFor(m => m[i].SerialNo)
                            @Html.HiddenFor(m => m[i].AssetTag)
                            @Html.HiddenFor(m => m[i].IsPickedUp)
                            @Html.HiddenFor(m => m[i].IsExtraPurchase)
                            @Html.HiddenFor(m => m[i].IsVendorBuyout)
                            @Html.HiddenFor(m => m[i].Notes)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model[i].TabletName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model[i].SerialNo)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model[i].AssetTag)
                        </td>
                        <td>
                            <label class="cellCheckBox">
                                @Html.CheckBoxFor(model => model[i].IsPurchased, new { @class = "scaledCheckBox" })
                            </label>
                        </td>
                        @*<td>
                            <label class="cellCheckBox">

                                @Html.CheckBoxFor(model => model[i].IsPickedUp, new { @class = "scaledCheckBox" })
                            </label>
                        </td>*@
                    </tr>
                }

            </tbody>
        </table>
        <div class="well well-sm form-group">
            <div class="col-md-10">
                <span class="icon-input-btn">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                    <input type="submit" value="Update" class="btn btn-primary" />
                </span>
                <span class="icon-input-btn">
                    <span class="glyphicon glyphicon-step-backward"></span>
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                </span>
            </div>
        </div>
    </div>
}
@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#indexTable").DataTable(
                {
                    // "dom": 'lfBpt<pi>',
                    "pagingType": "first_last_numbers",
                    //"columnDefs": [
                    //    { "orderable": false, "targets": [3,4] },

                    //],


                }
            );
            // Handle form submission event
            $('#batchUpdate').on('submit', function (e) {
                var form = this;
                $(document.body).css({ 'cursor': 'cursor-wait' });
                // Encode a set of form elements from all pages as an array of names and values
                var params = table.$('input').serializeArray();
                $('body').addClass('cursor-wait');
                // Iterate over all form elements
                $.each(params, function () {
                    // If element doesn't exist in DOM
                    if (!$.contains(document, form[this.name])) {
                        // Create a hidden element
                        $(form).append(
                            $('<input>')
                                .attr('type', 'hidden')
                                .attr('name', this.name)
                                .val(this.value)
                        );
                    }
                });
                $('body').removeClass('cursor-wait');
            });
        });

    </script>

}

TabletCollection/Views/Tablets/Create.cshtml
@model TabletCollection.ViewModels.TabletViewModel

@{
    ViewBag.Title = "Create";
}

<div class="row well">
    <div class="offset-1 col-1">
        
        <h2 class="text-primary">
            <span class="glyphicon glyphicon-floppy-open">&nbsp;</span>
            Create new tablet record
        </h2>
    </div>
    <div class="col-8">
        <p>tech: @User.Identity.Name | Date: @DateTime.Now.ToShortDateString() - @DateTime.Now.ToShortTimeString()</p>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TabletName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TabletName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TabletName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SerialNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SerialNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SerialNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AssetTag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AssetTag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AssetTag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsPurchased, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsPurchased)
                @Html.ValidationMessageFor(model => model.IsPurchased, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group well well-sm">
        <div class="col-md-offset-2 col-md-10">
            <span class="icon-input-btn">
                <span class="glyphicon glyphicon-floppy-saved"></span>
                <input type="submit" value="Create" class="btn btn-primary" />
            </span>
            <span class="icon-input-btn">
                <span class="glyphicon glyphicon-list"></span>
                @Html.ActionLink("To Tablet List", "Index", "Tablets", null, new { @class = "btn btn-default" })
            </span>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TabletCollection/Views/Tablets/Index.cshtml
@model IEnumerable<TabletCollection.ViewModels.TabletViewModel>

@{
    ViewBag.Title = "Index";
}

<div class="row well">
    <div class="row">
        <div class="offset-1 col-1">
            <h2 class="text-primary">Tablets</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-1 pull-left">
            <span class="icon-input-btn">
                <span class="glyphicon glyphicon-file"></span>
                @Html.ActionLink("Create New", "Create", "Tablets", null, new { @class = "btn btn-primary btn-sm" })
            </span>
        </div>
        @using (@Html.BeginForm(null, null, FormMethod.Get))
        {
            <div class="form-horizontal col-6 col-md-offset-6 pull-left">
                @Html.Label("filter", "Toggle to show All or Still to be Collected Tablets:", new { @class = "label label-default" })
                @Html.CheckBox("filter", false, new { data_toggle = "toggle", id = "filter", data_off = "All", data_on = "Not Collected", data_onstyle = "success", data_offstyle = "info", onchange = "this.form.submit()" })
            </div>
        }
    </div>
</div>

<table id="indexTable" class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TabletName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssetTag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsPurchased)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsExtraPurchase)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.IsPickedUp)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.IsVendorBuyout)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            @if (!(bool)ViewBag.Filter)
            {
                <th>
                    @Html.DisplayNameFor(m => m.IsTabletCollected)
                </th>
            }

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TabletName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SerialNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AssetTag)
                </td>
                <td>
                    @(item.IsPurchased ? "Yes" : "No")
                </td>
                <td>
                    @(item.IsExtraPurchase ? "Yes" : "No")
                </td>
                @*<td>
                    @(item.IsPickedUp ? "Yes" : "No")
                </td>*@
                <td>
                    @(item.IsVendorBuyout ? "Yes" : "No")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                @if (!(bool)ViewBag.Filter)
                {
                    <td>
                        @if (item.IsTabletCollected)
                        {
                            @Html.ActionLink("Yes", "Details", "Collections", new { id = item.CollectionID }, new { target = "_blank" })
                        }
                        else
                        {
                            @:No
    }
                    </td>
                }

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-default btn-xs" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-warning btn-xs" })
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{

    <script>
        // ViewBag.ExtraColumn
        var table;
        $(document).ready(function () {
            table = $("#indexTable").DataTable(
                {
                    // "dom": 'lfBpt<pi>',
                    "dom":
                        "<'row'<'col-sm-3 text-warning'l><'col-sm-3 text-primary'f><'col-sm-6'p>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-4 text-info'i><'col-sm-3 text-center'B><'col-sm-5'p>>",
                    buttons: [
                        'copy',
                        'excel',
                        'pdf'
                    ],
                    "columnDefs": [
                        { "orderable": false, "targets": @ViewBag.ExtraColumn  },
                        {
                            "targets": [2, 6],
                            "visible": false,
                            "searchable": false
                        },
                    ],
                    "pagingType": "first_last_numbers",

                }
            );
        });
        console.log(table.columns()[0].length);
    </script>

}